const data = {
    products:[
        {
            _id:'1',
            name:'Crystal Dice',
            image:'/images/product-1.jpg',
            price:12.99,
            seller:'Geraldine',
            seller_rating:3.2,
            rating_nums:58,
            description:'very pretty looking dice :3',
        },
        {
            _id:'2',
            name:'Cute Plush Bunny',
            image:'/images/product-2.jpg',
            price:9,
            seller:'Princess',
            seller_rating:2.2,
            rating_nums:58,
            description:'Adorable ;-;',
        },
        {
            _id:'3',
            name:'Cool Beans T-Shirt',
            image:'/images/product-3.jpg',
            price:6.66,
            seller:"Bob",
            seller_rating:3.1,
            rating_nums:58,
            description:'Cool as beans',
        },
        {
            _id:'4',
            name:'Mystery Box',
            image:'/images/product-4.jpg',
            price:19.51,
            seller:'Matt',
            seller_rating:1.9,
            rating_nums:58,
            description:'Buy it and you will find out...',
        },
        {
            _id:'5',
            name:'Green Dragon Miniature',
            image:'/images/product-5.jpg',
            price:21.95,
            seller:'Josh',
            seller_rating:4.3,
            rating_nums:58,
            description:'21cm wingspan',
        },
        {
            _id:'6',
            name:'Swole Doge',
            image:'/images/product-6.jpg',
            price:59.99,
            seller:'Kamil',
            seller_rating:4.9,
            rating_nums:58,
            description:'7 feet tall O.O',
        },        
        {
            _id:'7',
            name:'Less Swole Doge',
            image:'/images/product-6.jpg',
            price:49.99,
            seller:'Kamil',
            seller_rating:4.9,
            rating_nums:58,
            description:'7 feet tall :c',
        },        
    ]
}
export default data;